# JSON AI Schema Detector Configuration

# Порог для определения enum типов (количество различных значений)
enum_threshold: 10

# Формат выходного файла
output_format: "json-schema"

# Директория для сохранения схем
schemas_directory: "schemas"

# Сохранять комментарии при обновлении
preserve_comments: true

# Автоматическое определение полиморфных объектов
detect_polymorphic: true

# Строгая валидация
strict_validation: false 